AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  spoooooook-backend

  SAM Template for spoooooook-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  GetAllFilms:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: films/
      Handler: getAllFilms.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        GetAllFilms:
          Type: Api
          Properties:
            Path: /films
            Method: get

  GetFilm:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: films/
      Handler: getFilm.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        GetFilms:
          Type: Api
          Properties:
            Path: /film
            Method: get

  GetFilmLink:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: films/
      Handler: getFilmLink.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        GetFilmsLink:
          Type: Api
          Properties:
            Path: /film-link
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
